### Base URL
@GPMuseumify_HostAddress = http://localhost:5004

################################################################
### 1️⃣ Register
POST {{GPMuseumify_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "name": "esraa",
  "email": "Esraa.22120234@muc.edu.eg",
  "password": "123456"
}

### 2️⃣ Login 
POST {{GPMuseumify_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "alaa@example.com",
  "password": "Password123!"
}

### 3️⃣ Verify Email 
POST {{GPMuseumify_HostAddress}}/api/auth/verify-email
Content-Type: application/json

{
  "email": "420220485@fa-hists.edu.eg",
  "code": "4448"
}

### 4️⃣ Resend Verification Code 
POST {{GPMuseumify_HostAddress}}/api/auth/resend-verification
Content-Type: application/json

{
 
    "email": "420220340@fa-hists.edu.eg"
  
}

### 5️⃣ Forgot Password 
POST {{GPMuseumify_HostAddress}}/api/auth/forgot-password
Content-Type: application/json

{
  "email": "420220340@fa-hists.edu.eg"
}

### 6️⃣ Reset Password 
POST {{GPMuseumify_HostAddress}}/api/auth/reset-password
Content-Type: application/json

{
   
  "token": "7295",
  "newPassword": "12345678910"
}

### 7️⃣ Social Login 
POST {{GPMuseumify_HostAddress}}/api/auth/social-login
Content-Type: application/json

{
  "provider": "google",
  "token": "social_token_here"
}
### 8️⃣ Search Artifacts

POST {{GPMuseumify_HostAddress}}/api/search
Content-Type: application/json
{
"query": "ram",
  "type": "statue",
  "page": 1,
  "pageSize": 10
}

